[agent]
agent_type = "Qwen"
model = ""
name = "Qwen"
system_prompt = "You are a Rust programming expert."

[[mcp.tools]]
name = "sequential-thinking"
command = "npx"
args = ["-y", "@modelcontextprotocol/server-sequential-thinking"]

[mcp]
server = "https://mcp.docs.astro.build/mcp"
auth_token = "dummy-token"

[[mcp.tools]]
name = "weather"
command = "npx"
args = ["-y", "@h1deya/mcp-server-weather"]
